#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# dump the enviroment settings
export

# set a variable pointing to the bare repo
# we cannot work against the checkout, since it is a archive without .git
declare -x BARE_REPO="$HOME/git/$OPENSHIFT_APP_NAME.git"

# Gollum needs the git repo in its configuration. Using Perl and in place regular
# expression replacement we get the right value into config.ru. 
perl -pi -0777 -e "s@<repo>@$BARE_REPO@g" $OPENSHIFT_REPO_DIR/config.ru

